### ISSUE TITLE
Turn OHC notebook into tutorial

### ISSUE THREAD

**Issue by jukent** [NCAR/notebook-gallery#17]
Instead of teaching all the tools in the Pangeo toolbox independently and hoping people will synthesize them, I think there will be a greater reward and understanding if we teach use-cases and the tools necessary along the way. So I am turning the ocean-heat-content analysis into material for the tutorial. It will cover importing modules, dask chunking, xarray datasets and dataarrays (attrs, coords, dims, vars), Cf_Units, apply_ufunc, building functions, selecting data using where sel or isel, and plotting using xarray's built-in methods, matplotlib, or cartopy.

I think this should be done for every notebook in the notebook gallery. Maybe we have two separate files. One to cleanly and succinctly display the power of Pangeo and one to be more focused on education.

**Comment by dcherian** [comment]
+20.
