### ISSUE TITLE
WRF data example

### ISSUE THREAD

**Issue by jukent** [NCAR/notebook-gallery#20]
WRF metadata is formatted in a way not-easily read by Xarray. Ultimately we want to edit Xarray to understand these datasets, but let's create an example work around for WRF data time, lat, and lon coordinates, and how to plot data where x and y are 2-D. I have emailed Trude Eldhammer about using the notebook we worked on together during the tutorial as the example.

**Comment by jukent** [comment]
From Trude:
You can find the notebook here on Cheyenne:
/glade/u/home/trude/plot_precip_map.ipynb

and the two files here: 
/glade/work/trude/evoglac/idl/NETCDF_files/wrfinput_d02

and here:
/glade/work/trude/evoglac/WRF_output_2T_RR_F/all_T2_RR_F_2014_2019_SST.nc

**Comment by matt-long** [comment]
Have you looked at wrf-python?

**Comment by jukent** [comment]
Not yet but that is on my to-do. First this notebook might just be demonstrating the xarray method for the wrf data.
