### ISSUE TITLE
Make notebook-gallery data cached on Glade

### ISSUE THREAD

**Issue by bonnland** [NCAR/notebook-gallery#35]
Description: 

Users running notebook examples on a Cheyenne Compute Node will be unable to download data files using Pooch.  

Solution: 

Add a cache folder location to the Pooch fetch path.   The "fetch" method should check all folders in the path (the user's home folder location and the Glade location) before downloading the data file.

**Comment by bonnland** [comment]
@andersy005   Is it possible to have Pooch check multiple folders for the file before downloading to the specified cache folder?

**Comment by andersy005** [comment]
This issue was addressed in https://github.com/NCAR/notebook-gallery/pull/38
