### ISSUE TITLE
Try to integrate this with Pangeo Gallery?

### ISSUE THREAD

**Issue by rabernat** [NCAR/notebook-gallery#57]
Great repo!

It would be very cool to see if we could integrate this repo with [Pangeo Gallery](http://gallery.pangeo.io/). It shouldn't be too hard. What you would need is some branch in which the rendered notebooks are stored, plus a few configuration files. The details are described in the [contributor guide](http://gallery.pangeo.io/contributing.html#creating-a-new-gallery). The main difference would be that you wouldn't use binderbot--instead you would just manually build the notebooks on Cheyenne or wherever, then commit them directly to the branch and push to github. Then you would make a PR to add this repo as a submodule to `pangeo-gallery/pangeo-gallery`.

**Comment by bonnland** [comment]
@rabernat  Thanks for your help yesterday; I just tried updating the notebooks in the notebook-gallery, and it appears that the binderbot build does not get triggered when notebooks are updated in the main branch.   Is this a configuration issue, or are these rebuilds supposed to be run by hand?

Also, is the binderbot notebook execution supposed to save the cell outputs and include them in pangeo-gallery?   It would be very handy for notebook maintenance to not have to save them with outputs.

**Comment by rabernat** [comment]
> Is this a configuration issue, or are these rebuilds supposed to be run by hand?

It should happen automatically. Whether it runs is determined by the configuration of your workflow: https://github.com/NCAR/notebook-gallery/blob/main/.github/workflows/binderbot.yaml
It appears that your latest commit (https://github.com/NCAR/notebook-gallery/commit/d0c8cadf8de010fb4203f76e8dbfb9d1311286cf) did not trigger the workflow. I would look closely at the workflow configuration to understand why it didn't run, particularly these lines:

https://github.com/NCAR/notebook-gallery/blob/d0c8cadf8de010fb4203f76e8dbfb9d1311286cf/.github/workflows/binderbot.yaml#L2-L13


> Also, is the binderbot notebook execution supposed to save the cell outputs and include them in pangeo-gallery? It would be very handy for notebook maintenance to not have to save them with outputs.

Binderbot stores the executed notebooks with outputs in a dedicated branch on this repo:
https://github.com/NCAR/notebook-gallery/tree/binderbot-built
In terms of the workflow, this happens here:
https://github.com/NCAR/notebook-gallery/blob/d0c8cadf8de010fb4203f76e8dbfb9d1311286cf/.github/workflows/binderbot.yaml#L71-L84

The un-executed notebooks live in the main branch. So you have both at the same time.

To my eye, it looks like you have manually committed to the `binderbot-built` branch. There is a lot of stuff in there that has not been committed by binderbot.

**Comment by bonnland** [comment]
That is very helpful information; thanks!   It may be more than I can tackle today, but I am committed to figuring this stuff out soon.

**Comment by rabernat** [comment]
I recommend looking at the excellent github docs on workflows and then reading the binderbot workflow with this information in your mind. It is self-describing if you understand how workflows work.

**Comment by bonnland** [comment]
@rabernat   If I understand correctly, I believe the integration is complete or nearly complete.   But I could be missing something.    Any reasons to keep this issue open?
